sonar.projectKey=AsharAli-042_ashar-rizvi-mern-10pshine
sonar.organization=ashar-ali-rizvi

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.github/**,**/__tests__/**,**/*.test.js,**/*.test.jsx
