name: SonarCloud Analysis

on:
  push:
    branches: [ develop, main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Backend - install & coverage
        working-directory: ./backend
        run: |
          npm ci
          npm run coverage

      - name: Frontend - install & coverage
        working-directory: ./frontend
        run: |
          npm ci
          npm run test:coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: "ashar-ali-rizvi"
          projectKey: "AsharAli-042_ashar-rizvi-mern-10pshine"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
